apiVersion: v1
data:
  dbname: library
  #host: service-name.namespace.svc.cluster.local
  host: mysql.database:3306
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: restapi-cm
  namespace: restapi
